// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3YT4T0rzK1i_B2a63bA2Qu9crSiMsNRM',
    appId: '1:448114235861:web:969c3eaffe2ee487a9855c',
    messagingSenderId: '448114235861',
    projectId: 'thecart-5add1',
    authDomain: 'thecart-5add1.firebaseapp.com',
    storageBucket: 'thecart-5add1.appspot.com',
    measurementId: 'G-BYJYX8E4GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEMDcf8Rc6ObtojcphPpVnMM4l68SPUUQ',
    appId: '1:448114235861:android:3c2da8aea9305977a9855c',
    messagingSenderId: '448114235861',
    projectId: 'thecart-5add1',
    storageBucket: 'thecart-5add1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEiU-Ns87snWMNv5wFAc2nUYvsJK8l4wA',
    appId: '1:448114235861:ios:0113a6c9a9092350a9855c',
    messagingSenderId: '448114235861',
    projectId: 'thecart-5add1',
    storageBucket: 'thecart-5add1.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEiU-Ns87snWMNv5wFAc2nUYvsJK8l4wA',
    appId: '1:448114235861:ios:7277fc79fc7a0c21a9855c',
    messagingSenderId: '448114235861',
    projectId: 'thecart-5add1',
    storageBucket: 'thecart-5add1.appspot.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
