// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6ee50HsMTZ94uNOaFVbB9gcfbfDEEUnU',
    appId: '1:165169370813:web:ec10de6c62acae36a889d4',
    messagingSenderId: '165169370813',
    projectId: 'e-commerce-95335',
    authDomain: 'e-commerce-95335.firebaseapp.com',
    storageBucket: 'e-commerce-95335.appspot.com',
    measurementId: 'G-CQ8FJRCZQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRdTzG0sFiQx_acMRVI5st19yy8PEXmv4',
    appId: '1:165169370813:android:720372f4c7e9d07ca889d4',
    messagingSenderId: '165169370813',
    projectId: 'e-commerce-95335',
    storageBucket: 'e-commerce-95335.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXc_whwUvYreFccwh3QxDKDSEROACcFHA',
    appId: '1:165169370813:ios:9aeacca509e08234a889d4',
    messagingSenderId: '165169370813',
    projectId: 'e-commerce-95335',
    storageBucket: 'e-commerce-95335.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXc_whwUvYreFccwh3QxDKDSEROACcFHA',
    appId: '1:165169370813:ios:538c47971c6e6ed9a889d4',
    messagingSenderId: '165169370813',
    projectId: 'e-commerce-95335',
    storageBucket: 'e-commerce-95335.appspot.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
